# Stage 1: base
FROM python:3.10-slim AS base

# install system dependencies and Python packages
RUN apt-get update && apt-get install -y \
    libpq-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# Stage 2: api (later stages will use this base)
FROM base AS api
WORKDIR /app/api
COPY . .
CMD ["uvicorn", "app.api.api:api", "--host", "0.0.0.0", "--port", "8050"]

EXPOSE 8050

# Stage 3: dash
FROM base AS dash
WORKDIR /app/dash
COPY . .
CMD ["gunicorn", "-b", "0.0.0.0:8080", "app.dash.main:server"]

EXPOSE 8080
