services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_HOST=${HOSTDB}
      - POSTGRES_USER=${USERNAMEDB}
      - POSTGRES_PASSWORD=${DBPASSWD}
      - POSTGRES_DB=${DBNAME}
    ports:
      - "5434:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8050:8050"
    depends_on:
      - db
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "86:80"
    depends_on:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
