services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_HOST=${HOSTDB}
      - POSTGRES_USER=${USERNAMEDB}
      - POSTGRES_PASSWORD=${DBPASSWD}
      - POSTGRES_DB=${DBNAME}
    ports:
      - "5434:5432"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8050:8050"
    depends_on:
      - db
  dash:
    build:
      context: .
      dockerfile: Dockerfile-dash
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - api
