FROM python:3.10-slim

RUN apt-get update && apt-get install -y \
    libpq-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

# workdir
WORKDIR /app/dash

COPY ../../requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# copy dash code
COPY . .

# expose port
EXPOSE 8080

# run dash app
CMD ["gunicorn", "-b", "0.0.0.0:8080", "app.dash.main:server"]
# CMD ["python", "app/dash/main.py"]
