FROM python:3.10-slim AS base

RUN apt-get update && apt-get install -y \
    libpq-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

WORKDIR /app/api
COPY . .
EXPOSE 8050
CMD ["uvicorn", "app.api.api:api", "--host", "0.0.0.0", "--port", "8050"]

WORKDIR /app/dash
COPY . .
EXPOSE 8080
CMD ["gunicorn", "-b", "0.0.0.0:8080", "app.dash.main:server"]
