#!/usr/bin/env Rscript

ENV <- Sys.getenv("CITY") |>
  stringr::str_sub(start = 4)

loc <- glue::glue("data/{ENV}.csv")

df <- glue::glue(loc) |>
  readr::read_csv()

df_new <- df |> tidygeocoder::geocode(address = endereco, method = "arcgis",
                                      lat = "latitude", long = "longitude")

df_new |> write.csv(loc, row.names = FALSE)
