#! usr/bin/python3 

import os 
import sys
import argparse

parser = argparse.ArgumentParser(
		    prog="scraping-zap",
		    description="this is supposed to scrape zap imoveis, a real estate web site",
		    
		)
